### ISSUE TITLE
Is this not maintained anymore?

### ISSUE THREAD

**Issue by panda-dev24** [stalwartlabs/jmap-client#11]
There is no new commit since the last 7 months. The features like JMAP Blobs, Calenders and Contacts is not yet implemented (though some are not yet RFCs). So do I wait for it?

Also I am open to contribute in this repo to implement the said features if the original author is not able to.

**Comment by mdecimus** [comment]
This library needs a complete refactoring, sending request and receiving responses that combine multiple method calls is quite cumbersome. In addition to that there are plans to add WASM support to this library.
Development on this library has been paused but not abandoned. These tasks I mentioned, as well as adding support for all other JMAP protocols, is planned after Stalwart Mail Server reaches version 1.0 (hopefully around next year).

In the meantime feel free to contribute any missing features but do not spend much time on them as the refactoring might break them.

**Comment by panda-dev24** [comment]
Oh, okay. Thanks for reply. Will try to implement some features.
