### ISSUE TITLE
data did not match any variant of untagged enum SingleMethodResponse

### ISSUE THREAD

**Issue by arlyon** [stalwartlabs/jmap-client#5]
Hi! 

First of all, wow! This library is exceptional. I am trying to forego paying for sendgrid and using this to send emails via fastmail. I am running into an issue.

```rust
    let mailbox_id = client.mailbox_get("REDACTED", None::<Vec<Property>>).await.unwrap().unwrap().take_id();

    // Import a message into the mailbox.
    client
    .email_import(
        b"From: user@myemail.com\r\nSubject: test\r\n\r\n test".to_vec(),
        [&mailbox_id],
        ["$draft"].into(),
        None,
    )
    .await
    .unwrap();
```

I have found (through some logging) that the return data is as follows: 

```json
{"methodResponses":[["Email/import",{"notCreated":{},"accountId":"ID","created":{"i0":{"threadId":"ID","blobId":"G5211ba6f6add5bb3dfffa67ba0f045b5fe468e30","size":46,"id":"ID"}}},"s0"]],"latestClientVersion":"","sessionState":"ID"}
```

However, I am unable to actually get the message:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Parse(Error("data did not match any variant of untagged enum SingleMethodResponse", line: 1, column: 230))', src/main.rs:92:6
```

It seems that jmap-client::core::request is unable to cast the return type to a SingleMethodResponse. Any thoughts? It seems that fastmail does not return `newState` and so the untagged enum parsing fails.

**Comment by arlyon** [comment]
I have opened a support ticket with fastmail about this, as I believe this library is correct (https://jmap.io/spec-mail.html#emailimport)

**Comment by mdecimus** [comment]
Hi,

I agree, it looks like the `newState` field is missing and, according to the JMAP standard, this is a required field. You can also report this issue on the [Fastmail API topicbox](https://jmap.topicbox.com/groups/fastmail-api) which goes directly to the Fastmail developers.
